### ISSUE TITLE
Vector for unknown tokens

### ISSUE THREAD

**Issue by ecekt** [clips/dutchembeddings#1]
Hello, I was wondering if the token 'unk' in the COW models corresponds to the vector trained for unknown tokens. Or is it just a word encountered in the corpus? Best regards.

**Comment by stephantul** [comment]
Hi @ecekt,

We did not add any UNK tokens to the model vocabulary, so the vector of the token `unk` is in this case a (regrettable) result of the corpus containing the word unk in one if its sentences, and not a result of artificial inclusion. 

We did use a `min_count` argument for the COW corpus, but this does not result in the creation of `unk` tokens. Instead, words below the minimum count are dropped from the sentences including them.

Stéphan

**Comment by ecekt** [comment]
Hi Stéphan, thank you very much for the reply. Best.
