### ISSUE TITLE
no acces to word embedding sets

### ISSUE THREAD

**Issue by PascalVerkade** [clips/dutchembeddings#2]
There is no acces to the word embeddings with the links provided.
They result in the following webpage:
https://www.clips.uantwerpen.be/dutchembeddings/combined-320.tar.gz
which shows: 

Forbidden
You don't have permission to access this resource.
----------------------------------------------------------------------
Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 mod_perl/2.0.9 Perl/v5.22.1 Server at www.clips.uantwerpen.be Port 443

I'm quite desperate, I planned on using these sets in my bachalor thesis of my study (artificial intelligence, Utrecht University), but now I just found out that I don't have acces. Is there a way to receive this acces or the datasets?

Pascal Verkade
Bachelor student AI @ Utrecht University

**Comment by stephantul** [comment]
Hey @PascalVerkade, 

we are currently performing server maintenance. The word embeddings have been down since Friday and are expected to be up again later this week, maybe even tomorrow. I'll let you know once they are back up, but in case I forget, check back soon.

Best,
Stéphan

**Comment by rdatasculptor** [comment]
Hi @stephantul,

I guess the servers are still down? Any news about when they will be up again? Thanks!

**Comment by stephantul** [comment]
Should be fixed now.
