### ISSUE TITLE
Memory error. Op windows kan ik de most similar functie niet uitvoeren.

### ISSUE THREAD

**Issue by Thisgio** [clips/dutchembeddings#3]
Hoi,

Ik heb een probleem met het gebruiken van de embeddings. Ik weet haast zeker dat het met mijn lokale computer te maken heeft. Ik denk dat het om de overcomitting ratio gaat. Nou weet ik niet hoe of dat ik deze kan aanpassen in windows.

Kan een van jullie mij misschien op weg helpen?

Groeten,

Giovanni

**Comment by stephantul** [comment]
Hoi Giovanni, 

kan je misschien beschrijven hoe je de modellen inlaadt (met welk pakket/code), en welk model je probeert in te laden? Als je een memory error ziet, dan betekent dat dat je niet genoeg RAM-geheugen hebt. Je kan dit eventueel verhelpen door een kleiner model te selecteren (als je nu bijv. `COW-big` gebruikt kan je misschien bijv. `Wikipedia-160` gebruiken.)

Groet,
Stéphan

**Comment by Thisgio** [comment]
Stephan,

Ik implementeer het model op deze manier: 

```
# Gensim
import gensim

model = gensim.models.KeyedVectors.load_word2vec_format("./Embeddings/160/wikipedia-160.txt", binary=False)
katvec = model['kat']
x = model.most_similar('kat')


```
Dit is de error bij een van een vector size van 100:

Exception has occurred: MemoryError
Unable to allocate 996. MiB for an array with shape (2610658, 100) and data type float32
  File "D:\Source\Repos\DataAugmentation\Embeddings.py", line 14, in <module>
    x = model.most_similar('kat')

Bij de vector van 100 gaat die al zeuren.

Enig idee wat ik zou kunnen doen?

Groeten,

Giovanni

**Comment by stephantul** [comment]
Hoi, 

Kan je uitleggen hoe je de vector size hebt aangepast naar 100? Dit zou normaal 160 moeten zijn.

Je systeem heeft wellicht gewoon te weinig geheugen. De wikipedia file bevat meer dan 1 miljoen woorden. Als je dat wilt, kan je een subset van die woorden inladen, dan zouden je geheugenproblemen opgelost moeten zijn. Dit zou ook niet echt een probleem moeten zijn voor de meeste toepassingen, omdat de woorden die je weglaat hoogstwaarschijnlijk laag-frequente termen zijn.

Dit kan je bij gensim met de `limit` parameter doen, bijv.

```python
model = gensim.models.KeyedVectors.load_word2vec_format("./Embeddings/160/wikipedia-160.txt", binary=False, limit=1000)
```

**Comment by Thisgio** [comment]
Stephan,

Het probleem is opgelost door de limit!

Ik had even een ander model gepakt die een size had van 100. Nu gebruik ik weer de wikipedia.

Bedankt :).

Groeten,

Giovanni
