### ISSUE TITLE
Download links down 

### ISSUE THREAD

**Issue by Noixas** [clips/dutchembeddings#4]
The download links for all the embeddings are not working.
![image](https://user-images.githubusercontent.com/23318473/82648679-4e98b400-9c18-11ea-9c15-6caf2c4a1ea2.png)

**Comment by stephantul** [comment]
Hi. They are still accessible, but you need to manually reinsert the `/` between `www.clips.uantwerpen.be` and `dutchembeddings`. Somehow, the slash is getting clobbered. I'll investigate. For now you can fix it yourself by downloading from `www.clips.uantwerpen.be/dutchembeddings`.

**Comment by cmry** [comment]
@stephantul probably not a bad idea to have a mirror up, I can handle this if you want :)

**Comment by stephantul** [comment]
@cmry alright, that would be great. thanks!

**Comment by cmry** [comment]
http -> https rewrite bs on the uantwerpen server, fixed in 83d610f2ccd9a6b68f96c5b8dafe523986f9f1c6
