### ISSUE TITLE
Usage example needs to use KeyedVectors for newer versions of gensim

### ISSUE THREAD

**Issue by VeraOtter** [clips/dutchembeddings#5]
Hi, thanks for sharing these materials. For me the usage example with gensim did not work and I found out it is because in newer versions of gensim the load_word2vec_format() function is moved under gensim.models.KeyedVectors instead of under Word2Vec.

**Comment by cmry** [comment]
Hi Vera, thanks for reporting! The examples have been updated to reflect the new gensim API per 9625c10.
